---
- hosts: ec2
  become: yes
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3  # Use Python 3 everywhere

  tasks:
    # 1. Ensure Python 3 is installed
    - name: Install Python 3 on Amazon Linux
      raw: |
        if ! command -v python3 &> /dev/null; then
          sudo yum install -y python3 || \
          (sudo amazon-linux-extras enable python3.8 && sudo yum install -y python3)
        fi

    # 2. Gather facts now that Python 3 is present
    - name: Gather facts (after installing Python 3)
      setup:

    # 3. Update all system packages
    - name: Update system packages
      command: sudo yum update -y

    # 4. Install Docker
    - name: Install Docker
      command: sudo yum install -y docker

    # 5. Start and enable Docker
    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: true

    # 6. Add ec2-user to Docker group
    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    # 7. Create application directory
    - name: Create application directory
      file:
        path: /opt/marketmap
        state: directory
        mode: '0755'

    # 8. Verify Docker installation
    - name: Check Docker version
      command: docker --version
      register: docker_version

    - name: Display Docker version
      debug:
        msg: "Docker version: {{ docker_version.stdout }}"
